all:
  vars:
    platform: kubernetes
    ansible_connection: local
  hosts:
    west:
      kubeconfig: /tmp/skewer/kubeconfig-west
      namespace: west
    east:
      kubeconfig: /tmp/skewer/kubeconfig-east
      namespace: east
      links:
        - host: west
      services:
        backend:
          ports:
            - 8080
          targets:
            - type: deployment
              name: backend
