all:
  vars:
    ansible_connection: local
  hosts:
    east:
      kubeconfig: "{{ inventory_dir }}/kubeconfigs/east"
      namespace: east
      links:
        - host: west
      services:
        backend:
          ports:
            - 8080
          targets:
            - type: deployment
              name: backend
    west:
      kubeconfig: "{{ inventory_dir }}/kubeconfigs/west"
      namespace: west
