- hosts: west
  tasks:
    - command: "kubectl apply -f {{ playbook_dir }}/kubernetes/west.yaml"

- hosts: east
  tasks:
    - command: "kubectl apply -f {{ playbook_dir }}/kubernetes/east.yaml"

- hosts: all
  collections:
    - skupper.network
  tasks:
    - import_role:
        name: skupper
