- hosts: all
  collections:
    - skupper.network
  tasks:
  - import_role:
      name: skupper_delete

- hosts: west
  tasks:
    - command: "kubectl delete -f {{ playbook_dir }}/kubernetes/west.yaml"

- hosts: east
  tasks:
    - command: "kubectl delete -f {{ playbook_dir }}/kubernetes/east.yaml"
